packages:
  - packages/*/*

onlyBuiltDependencies:
  - '@confluentinc/kafka-javascript'
  - '@nestjs/core'
  - '@parcel/watcher'
  - '@scarf/scarf'
  - core-js
  - esbuild
  - nx
  - protobufjs
  - sqlite3
