packages:
  - packages/*/*
  - .tools/*

allowBuilds:
  '@confluentinc/kafka-javascript': set this to true or false
  '@nestjs/core': set this to true or false
  '@scarf/scarf': set this to true or false
  core-js: set this to true or false
  esbuild: set this to true or false
  nx: set this to true or false
  protobufjs: set this to true or false
  sqlite3: set this to true or false

onlyBuiltDependencies:
  - '@confluentinc/kafka-javascript'
  - '@nestjs/core'
  - '@parcel/watcher'
  - '@scarf/scarf'
  - core-js
  - esbuild
  - nx
  - protobufjs
  - sqlite3
