version: '3'
services:
  postgres1:
    image: postgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USER: 'postgres'
  postgres2:
    image: postgres
    ports:
      - 5434:5432
    environment:
      POSTGRES_DB: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USER: 'postgres'
  postgres3:
    image: postgres
    ports:
      - 5435:5432
    environment:
      POSTGRES_DB: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USER: 'postgres'
